---
# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.0
    hooks:
      - id: reuse

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: trailing-whitespace

  # Terraform
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.77.0
  #   hooks:
  #     - id: terraform_fmt

  # YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: ["--strict"]
